INSERT INTO USUARIOS(ID_USUARIO, USER_NAME, PASSWORD, ROLE) VALUES (100, 'alexandre@teste.com', '123456', 'ROLE_ADMIN');
INSERT INTO USUARIOS(ID_USUARIO, USER_NAME, PASSWORD, ROLE) VALUES (101, 'teste2@teste.com', '123456', 'ROLE_CLIENTE');
INSERT INTO USUARIOS(ID_USUARIO, USER_NAME, PASSWORD, ROLE) VALUES (102, 'teste3@teste.com', '123456', 'ROLE_CLIENTE');