INSERT INTO USUARIOS(ID_USUARIO, USER_NAME, PASSOWORD, ROLE) VALUE(100, 'alexandre@teste.com', '123456', 'ROLE_ADM');
INSERT INTO USUARIOS(ID_USUARIO, USER_NAME, PASSOWORD, ROLE) VALUE(101, 'teste2@teste.com', '123456', 'ROLE_CLIENTE');
INSERT INTO USUARIOS(ID_USUARIO, USER_NAME, PASSOWORD, ROLE) VALUE(102, 'teste3@teste.com', '123456', 'ROLE_CLIENTE');